backend:
  name: git-gateway
  branch: master
  squash_merges: true
publish_mode: editorial_workflow
media_folder: "source/assets/images/uploads"
public_folder: "assets/images/uploads"

collections:
  - name: "testimonials"
    label: "Testimonials"
    label_singular: "Testimonial"
    folder: "source/_testimonials"
    create: true
    identifier_field: "author"
    slug: "{{slug}}"
    extension: "md"
    format: "yaml-frontmatter"
    fields:
      - {label: "Author", name: "author", required: true, widget: "string"}
      - {label: "Position", name: "position", widget: "string", default: "Position"}
      - {label: "Link", name: "link", widget: "string", default: "Link"}
      - {label: "Image", name: "img", widget: "string", required: true}
      - {label: "Body", name: "content", widget: "markdown"}